services:
  chat-tutor:
    container_name: chat-tutor
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3012:3012
    networks:
      - app-network

  chat-db:
    container_name: chat-db
    restart: unless-stopped
    image: postgres:17
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    name: app-network
