services:
  chat-tutor:
    container_name: chat-tutor
    profiles:
      - production
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3012:3012
    # depends_on:
    #   - chat-db-production
    networks:
      - app-network

  chat-tutor-dev:
    container_name: chat-tutor-dev
    profiles:
      - dev
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./prisma:/app/prisma
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./package.json
    depends_on:
      - chat-db
    networks:
      - app-network

  chat-db:
    container_name: chat-db
    restart: unless-stopped
    image: postgres:17
    profiles:
      - dev
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ../volumes/postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    name: app-network
